development:
  adapter: postgresql
  database: goodblogdev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: goodblogtest
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: goodblogprod
  pool: 5
  timeout: 5000

